@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName
 -myTime
 -goodMorning
 -goodAfternoon
 -goodNight
 -hirstValue
 -2つ目の整数
 -足し算の結果

 +getMyName()
 +setMyName()
 +setNewTime()
 +getMyGreeting()
 +setSecondValue()
 +setAddition()
 +getAddition()
}

@enduml
